use crate::cmd::{app, bookmark_list, file, filer, input};
use crate::state::AppState;
use anyhow::Result;

pub enum Command {
    MoveCursorUp,
    MoveCursorDown,
    MoveCursorLeft,
    MoveCursorRight,
    EnterFile,
    ChangeParentDir,
    RefreshFiles,
    ToggleCheckedFile,
    ToggleDotFiles,
    AddBookmark,
    RemoveBookmark,
    ShowBookmarkList,
    CloseBookmarkList,
    BookmarkCursorUp,
    BookmarkCursorDown,
    InputCopy,
    InputDelete,
    InputMkdir,
    InputMove,
    InputRename,
    InputSort,
    InputChar(char),
    InputBackspace,
    InputTab,
    InputSelectLeft,
    InputSelectRight,
    InputOk,
    InputCancel,
    InputSearch,
    InputSearchNext,
    InputSearchPrev,
    Quit,
    None,
}

impl Command {
    pub fn exec(self, state: &mut AppState) -> Result<()> {
        match self {
            Command::MoveCursorUp => filer::up_cursor(state),
            Command::MoveCursorDown => filer::down_cursor(state),
            Command::MoveCursorLeft => filer::first_cursor(state),
            Command::MoveCursorRight => filer::last_cursor(state),
            Command::EnterFile => file::enter_file(state),
            Command::ChangeParentDir => filer::change_to_parent(state),
            Command::RefreshFiles => filer::refresh_files(state),
            Command::ToggleCheckedFile => filer::toggle_checked_file(state),
            Command::ToggleDotFiles => filer::toggle_dot_files(state),
            Command::AddBookmark => filer::add_bookmark(state),
            Command::RemoveBookmark => filer::remove_bookmark(state),
            Command::ShowBookmarkList => bookmark_list::show(state),
            Command::CloseBookmarkList => bookmark_list::close(state),
            Command::BookmarkCursorUp => bookmark_list::up_cursor(state),
            Command::BookmarkCursorDown => bookmark_list::down_cursor(state),
            Command::InputCopy => input::input_copy(state),
            Command::InputDelete => input::input_delete(state),
            Command::InputMkdir => input::input_mkdir(state),
            Command::InputMove => input::input_move(state),
            Command::InputRename => input::input_rename(state),
            Command::InputSort => input::input_sort(state),
            Command::InputChar(c) => input::input_char(state, c),
            Command::InputBackspace => input::input_backspace(state),
            Command::InputTab => input::input_tab(state),
            Command::InputSelectLeft => input::input_select_left(state),
            Command::InputSelectRight => input::input_select_right(state),
            Command::InputOk => input::input_ok(state),
            Command::InputCancel => input::input_cancel(state),
            Command::InputSearch => input::input_search(state),
            Command::InputSearchNext => input::input_search_next(state),
            Command::InputSearchPrev => input::input_search_prev(state),
            Command::Quit => app::quit(state),
            Command::None => Ok(()),
        }
    }
}
