name: "docs: ドキュメントの変更"
description: ドキュメントの追加・修正
labels: ["docs"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: ドキュメントの変更内容を記述してください
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 詳細
      description: 変更の詳細や理由を記述してください
