name: "fix: 不具合修正"
description: バグの報告
labels: ["fix"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 不具合の概要を記述してください
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 不具合を再現する手順を記述してください
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      description: 本来どのように動作すべきかを記述してください
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際にどのように動作したかを記述してください
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: OS、Rustバージョンなど関連する環境情報を記述してください
